name: dweller
description: "Dweller App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  #state management
  get: ^4.6.0
  
  #otp textfield (awesome package)
  flutter_otp_text_field: ^1.1.1

  #for picking documents
  file_picker: ^3.0.0
  path_provider: ^2.1.1

  
  #ui customizations
  google_fonts: ^6.0.0
  dots_indicator: ^2.1.1
  flutter_svg: ^2.0.7
  dotted_border: ^2.1.0
  timeago: ^3.6.1
  gradient_elevated_button: ^1.0.0
  #lottie: ^2.7.0
  flutter_speed_dial: ^7.0.0
  flutter_xlider: ^3.5.0

  #for swiping just like Tinder(Awesome Package)
  appinio_swiper: ^2.1.1
  
  #for nice loadimg animation and shimmer effect
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.0.0+2


  #country pickers
  country_code_picker: ^3.0.0
  country_picker: ^2.0.22
  #currency_picker: ^2.0.20

  #for launching urls, phone number and emails
  url_launcher: ^6.1.14

  #for local storage(Better than SharedPreference)
  get_storage: ^2.0.3

  #date and time packages (very awesome packages)
  calendar_date_picker2: ^0.5.3
  duration_picker: ^1.1.1

  #for converting date/time objects nicely including servertime stamps
  date_time_format: ^2.0.1

  #websockets or socket.io for chatting feature
  socket_io_client: ^2.0.3+1

  #for network calls and jwt decoder and http parser
  #http: ^1.2.2
  http: ^1.1.2
  http_parser: ^4.1.0
  dio: ^5.4.0
  jwt_decoder: ^2.0.1

  #to check everything about your jwt and manage session expiry
  flutter_session_jwt: ^0.0.6

  #for google auth
  google_sign_in: ^6.1.6
  

  #for images
  cached_network_image: ^3.3.0
  cloudinary: ^1.2.0
  image_picker: ^1.0.7
  #image_picker_web: ^3.1.1
  

  #for generating qr codes
  #qr_flutter: ^4.1.0

  #rating_bar indicator and screen util
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0

  #for sharing anything sharable
  share_plus: ^7.2.1

  #firebase apis
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  googleapis_auth: ^1.6.0
  firebase_auth: ^4.15.0

  #(foreground)local notifications)
  flutter_local_notifications: ^17.2.2

  #stripe payment api (do stripe configuration for android & iOS first)
  #flutter_stripe: ^10.1.1

  #google maps the oga
  google_maps_flutter: ^2.7.0

  
dependency_overrides:
  intl: ^0.18.0
  
  #http: ^1.2.2
  http: ^1.1.2
  http_parser: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  #for updating launcher icons
  flutter_launcher_icons: ^0.13.1
  #change app manifest package name
  change_app_package_name: ^1.1.0


flutter_launcher_icons:
  #android: "launcher_icon"
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon_logo.png"


flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
