// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79Y5yW9H7CxWirbkNvW3E5rnoHD6E5g0',
    appId: '1:916549846966:web:4ac9a1da358ddbc9c82317',
    messagingSenderId: '916549846966',
    projectId: 'dwellers-61d22',
    authDomain: 'dwellers-61d22.firebaseapp.com',
    storageBucket: 'dwellers-61d22.appspot.com',
    measurementId: 'G-TT9LCGSCRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMl3z7VSvns6sKcuf5u1GX1379baici24',
    appId: '1:916549846966:android:ee70ceb357e28f65c82317',
    messagingSenderId: '916549846966',
    projectId: 'dwellers-61d22',
    storageBucket: 'dwellers-61d22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAMaXu80RdN7VusRzN6U3_y4AwdJgt6M',
    appId: '1:916549846966:ios:fadeedf694c0c53ac82317',
    messagingSenderId: '916549846966',
    projectId: 'dwellers-61d22',
    storageBucket: 'dwellers-61d22.appspot.com',
    iosBundleId: 'com.example.dweller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaAMaXu80RdN7VusRzN6U3_y4AwdJgt6M',
    appId: '1:916549846966:ios:fadeedf694c0c53ac82317',
    messagingSenderId: '916549846966',
    projectId: 'dwellers-61d22',
    storageBucket: 'dwellers-61d22.appspot.com',
    iosBundleId: 'com.example.dweller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC79Y5yW9H7CxWirbkNvW3E5rnoHD6E5g0',
    appId: '1:916549846966:web:3512d33897ece25fc82317',
    messagingSenderId: '916549846966',
    projectId: 'dwellers-61d22',
    authDomain: 'dwellers-61d22.firebaseapp.com',
    storageBucket: 'dwellers-61d22.appspot.com',
    measurementId: 'G-RWGCK24GYC',
  );
}
